### PR TITLE
instance MonadPlus Input

### LINKED ISSUE #31: MonadPlus instance for Input
Should be trivial, since `Input` already has instances for both `Monad` and `Alternative`.

### PR DESCRIPTION
**Pull request by pthariensflame**
Closes #31.

### CODE REVIEW

**Comment by Gabriel439** [comment]
Thanks a lot for writing that up! :)

**Comment by Gabriel439** [comment]
Oops, it looks like it is missing an import, but I'll fix it.

**Comment by Gabriel439** [comment]
Alright.  This is fixed and up on Hackage as `pipes-concurrency-2.0.3`.

**Comment by pthariensflame** [comment]
Whoops!  And thanks!  :)

**Comment by Gabriel439** [comment]
You're welcome! :)

**Pull request merged**
